apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
patchesStrategicMerge:
- broadcaster-patch.yaml
- route-patch.yaml
namespace: staging
patches:
- path: db-cronjob-patch.yaml
  target:
    kind: CronJob
    name: add-random-todo
images:
- name: broadcaster
  newName: kylmps/broadcaster
  newTag: "1.0"
- name: todo-backend
  newName: kylmps/todo-backend
  newTag: "4.3"
- name: todo-frontend
  newName: kylmps/todo-frontend
  newTag: "5.9"
