apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
type: Opaque
stringData:
  webhook-url: "https://discord.com/api/webhooks/1392384184894361710/_Pyzs0-vm74P2rmDwklTCjNzFb5fTHBWq5vmvLOIuwI84hoKcoK84Tej5OjF4AbUawq" # This will be encrypted