apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          # image: kylmps/broadcaster:2.0 
          image: broadcaster
          env:
            - name: NATS_URL
              value: "nats://my-nats.default.svc.cluster.local:4222" # Corrected for cross-namespace communication
            # OLD: value: "nats://my-nats:4222"
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-webhook-secret
                  key: webhook-url